
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_mes?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  thymeleaf:
    cache: false
server:
  servlet:
    session:
      timeout: -1
    context-path: /
  port: 8010



